from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from virtual_staining.experiment.run_context import RunContext
    from virtual_staining.training.results import EpochMetrics, TrainingResult


@runtime_checkable
class Reporter(Protocol):
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def metric(self, name: str, value: float, step: int | None = None) -> None: ...
    def artifact(self, path: Path, kind: str) -> None: ...


@runtime_checkable
class TrainingReporter(Reporter, Protocol):
    def on_training_started(self, context: RunContext) -> None: ...
    def on_epoch_completed(self, metrics: EpochMetrics) -> None: ...
    def on_checkpoint_saved(self, path: Path, epoch: int) -> None: ...
    def on_training_completed(self, result: TrainingResult) -> None: ...
