from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

import torch

from virtual_staining.config.losses import LossConfig


@dataclass(frozen=True)
class MethodMetrics:
    """Named method-owned metrics returned to generic training orchestration."""

    losses: dict[str, float]
    component_totals: dict[str, float] = field(default_factory=dict)
    raw: dict[str, float] = field(default_factory=dict)
    weighted: dict[str, float] = field(default_factory=dict)
    current_weight: dict[str, float] = field(default_factory=dict)
    image: dict[str, float] = field(default_factory=dict)


class TrainingMethodRuntime(Protocol):
    """Behavior owned by one concrete translation method during training."""

    @property
    def name(self) -> str: ...
    @property
    def pairing(self) -> str: ...
    @property
    def input_names(self) -> tuple[str, ...]: ...
    @property
    def output_names(self) -> tuple[str, ...]: ...
    @property
    def prediction_directions(self) -> tuple[str, ...]: ...
    @property
    def default_checkpoint_metric(self) -> str: ...
    @property
    def metric_names(self) -> Sequence[str]: ...
    @property
    def component_total_names(self) -> Sequence[str]: ...
    @property
    def loss_names(self) -> Sequence[str]: ...
    @property
    def loss_config(self) -> LossConfig: ...

    def train_mode(self) -> None: ...
    def batch_size(self, batch: object) -> int: ...
    def step(self, batch: object, *, epoch: int, global_step: int) -> MethodMetrics: ...
    def validate(
        self,
        loader: torch.utils.data.DataLoader,
        *,
        epoch: int,
        output_dir: Path,
    ) -> MethodMetrics: ...
    def validation_metric(self, metrics: MethodMetrics, name: str) -> float | None: ...
    def checkpoint_selection_metrics(self, metrics: MethodMetrics) -> dict[str, float]: ...
    def checkpoint_selection_modes(self) -> dict[str, str]: ...
    def step_schedulers(
        self,
        *,
        epoch: int,
        validation_metrics: MethodMetrics | None,
    ) -> bool: ...
    def learning_rates(self) -> Mapping[str, float]: ...
    def component_metadata(self) -> Mapping[str, object]: ...
    def state_dict(self) -> dict[str, Any]: ...
    def load_state_dict(self, state: Mapping[str, Any]) -> None: ...
